deepmodeling/reacnetgenerator

.gitignore, .travis.yml, docs/README.md, reacnetgenerator/test.py, setup.cfg, setup.py
=> add test scripts

reacnetgenerator/reacnetgen.py, reacnetgenerator/test.py, setup.py
=> check md5 when testing

docs/README.md, reacnetgenerator/reacnetgen.py, setup.py
=> tqdm (fix #39)

reacnetgenerator/reacnetgen.py
=> use logging package

reacnetgenerator/__init__.py
some scipy versions may meet this error
=> fix: avoid qhull library error

docs/.vuepress/public/reacnetgen.svg
/docs/.vuepress/public/reacnetgen.svg -- 1.70kb -> 1.54kb (9.2%)
Signed-off-by: ImgBotApp <ImgBotHelp@gmail.com>
=> chore:[ImgBot] Optimize images

reacnetgenerator/_path.py
=> fix: bugfix in smiles converting

conda/recipe/meta.yaml
=> make the python version <=3.8?

reacnetgenerator/_detect.py, reacnetgenerator/commandline.py, reacnetgenerator/reacnetgen.py
Example:
```bash
reacnetgenerator -i H2O-32-pos-1.xyz -a H O --nohmm -t xyz -c 9.8528 9.8528 9.8528
```
=> fix: support xyz format

reacnetgenerator/_detect.py
modify the periodic boundary to deal with the triclinic system
=> fix: support triclinic cell

reacnetgenerator/utils.py
until scour-project/scour#260 is fixed
=> chore: set strip_ids to False

reacnetgenerator/utils.py
Reverts tongzhugroup/reacnetgenerator#778
=> revert: "chore: set strip_ids to False"

reacnetgenerator/_reachtml.py
Co-authored-by: Hesy <hesy519@gmail.com>
=> fix: fix SMILES converting bug (resolve #1056)

reacnetgenerator/_reachtml.py
=> fix: processing two-character elements

reacnetgenerator/_reachtml.py, reacnetgenerator/test/test_reacnetgen.py
=> fix: fix two-character elements

reacnetgenerator/commandline.py
Reverts tongzhugroup/reacnetgenerator#1652
It doesn't work as expected.
=> Revert "add GUI cli to main cli"

reacnetgenerator/_hmmfilter.py
hmmlearn v0.2.8 renamed MultinomialHMM to CategoricalHMM
=> fix compatible with hmmlearn v0.2.8

pyproject.toml, setup.py
- migrate from setup.py to pyproject.yaml
- requires setuptools_scm
=> migrate from setup.py to pyproject.yaml

reacnetgenerator/static/webpack/package.json, reacnetgenerator/static/webpack/webpack.config.js, reacnetgenerator/static/webpack/yarn.lock
=> remove precss

reacnetgenerator/_path.py, reacnetgenerator/_reachtml.py, reacnetgenerator/reacnetgen.py, reacnetgenerator/static/webpack/reacnetgen.js
=> switch to VF2; fallback when RDKit throws error

reacnetgenerator/static/webpack/reacnetgen.js
=> limit the size of options in a select to 65536

conda/recipe/meta.yaml, pyproject.toml, reacnetgenerator/_detect.py, reacnetgenerator/reacnetgen.py
Removes scipy from dependencies.
=> use openbabel native pbc implementation

Dockerfile
=> fix: fix and minify docker images

reacnetgenerator/static/webpack/package.json, reacnetgenerator/static/webpack/yarn.lock
Reverts tongzhugroup/reacnetgenerator#1819
=> Revert "Update dependency smiles-drawer to v2.1.2"

reacnetgenerator/static/webpack/reacnetgen.css
per https://github.com/superRaytin/paginationjs/issues/138
=> improve `.paginationjs` style

.pre-commit-config.yaml, reacnetgenerator/_detect.py, reacnetgenerator/reacnetgen.py, reacnetgenerator/utils.py
- add hook to format numpydoc
- format numpy docs
=> format numpydoc

.github/workflows/push.yml, Dockerfile, pyproject.toml
Reverts tongzhugroup/reacnetgenerator#1878
=> Revert "revert Python to 3.10 for hmmlearn"

Dockerfile
Reverts tongzhugroup/reacnetgenerator#2021
=> Revert "chore(deps): update python docker tag to v3.12"

.pre-commit-config.yaml, pyproject.toml, reacnetgenerator/_hmmfilter.py, reacnetgenerator/reacnetgen.py
See https://astral.sh/blog/the-ruff-formatter
=> move to ruff format

reacnetgenerator/_reachtml.py
=> set encoding to utf-8 when opening package data

reacnetgenerator/_path.py, reacnetgenerator/_reachtml.py, tests/test.json, tests/test_reacnetgen.py
=> breaking: remove implicit Hs from RDKit SMILES
